### ISSUE TITLE
Linked Files Crash Server

### ISSUE THREAD

**Issue by jim-manley** [lionaneesh/RasPod#2]
If a soft link (e.g. ln -s) is placed in the Media directory to a file elsewhere in the file hierarchy, the server crashes during startup.  Apparently, all files must be in the same level of the Media directory, while most media file systems (e.g., iTunes) allow files to be organized hierarchically (e.g., by a directory per album, with albums by one artist all within one directory).

It would be great if RasPod could walk down through directory hierarchies when playing files.  Also, when files are added, they aren't accessible until the server is restarted and it would be really nice if the file list were refreshed each time the player page is reloaded in a browser (or provide a file list Refresh button).

**Comment by lionaneesh** [comment]
First of all, thanks @jim-manley for using RasPod and taking the pain of reporting the bug, much appreciated.

> If a soft link (e.g. ln -s) is placed in the Media directory to a file elsewhere in the file hierarchy, the server crashes during startup.

Fixed in 7bd3bd8f5a32731bd66739f8153181aa10d909ca

> Apparently, all files must be in the same level of the Media directory

That's not true, you can add as many directory levels, inside the Media directory, as you want. I just verified it and it 
works as expected.

Your other feature requests will be worked on in the following days.

**Comment by lionaneesh** [comment]
Your feature-requests have been reported in #4 and #5 . I am closing this issue now. Please comment back if you are still facing some problems, or have something to add.

Thanks once again.
